language = "javascript"
status = "alpha"

[documentation]
description  = """
JavaScript driver for [babelfish](https://github.com/bblfsh/bblfshd).
"""

[runtime]
os = "alpine"
go_version = "1.8"
native_version = ["6.10.3-r1"]
